name: ca-primary-care
channels:
  - conda-forge
dependencies:
  - ipykernel
  - r-base
  - r-plotly
  - r-tidyverse
  - r-languageserver
  - r-shiny
  - r-openxlsx
  - r-bslib
  - r-ggthemes
  - r-rsconnect