# Exploring the Data

## Development of `src/process_data.R`.

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)
library(ggthemes)
```

```{r}
# url <- "https://www.cihi.ca/sites/default/files/document/health-workforce-canada-2019-2023-overview-data-tables-en.xlsx"
# download.file(url, "../data/raw/raw_data.xlsx", mode = "wb")
```

```{r}
# raw_data_ <- read_excel("../data/raw/raw_data.xlsx", sheet=3, skip=1, n_max=37)
```

```{r}
# raw_nl_data <- read.xlsx(
#   "../data/raw/raw_data.xlsx",
#   sheet=4,
#   startRow=2,
#   rows=seq(2, 185),
#   fillMergedCells = TRUE)
# 
# processed_nl_data <- raw_nl_data
# 
# colnames(processed_nl_data) <- c("profession_type",
#                                  "year",
#                                  "count",
#                                  "count_per_100000",
#                                  "percent_female",
#                                  "percent_age_under_30",
#                                  "percent_age_30_to_59",
#                                  "percent_age_over_60") 
# 
# processed_nl_data <- processed_nl_data |>
#   filter(profession_type == "Family medicine" |
#         profession_type == "Nurse practitioners") |>
#   mutate(province_territory = "Newfoundland and Labrador")
```

```{r}

# read_save_process_province_territory_data <- function(sheet_number, name) {
#   raw_province_territory_data <- read.xlsx(
#     "../data/raw/raw_data.xlsx",
#     sheet=sheet_number,
#     startRow=2,
#     rows=seq(2, 185),
#     fillMergedCells = TRUE) |>
#     select(1:8)
#   
#   processed_province_territory_data <- raw_province_territory_data
#   
#   colnames(processed_province_territory_data) <- c(
#     "profession_type",
#     "year",
#     "count",
#     "count_per_100000",
#     "percent_female",
#     "percent_age_under_30",
#     "percent_age_30_to_59",
#     "percent_age_over_60") 
# 
#   processed_province_territory_data <- processed_province_territory_data |>
#     filter(profession_type == "Family medicine" |
#     profession_type == "Nurse practitioners") |>
#     mutate(province_territory = name)
#   
#   return(processed_province_territory_data)
# }
```

```{r}
# names <- c("Newfoundland and Labrador",
#            "Prince Edward Island",
#            "Nova Scotia",
#            "New Brunswick",
#            "Quebec",
#            "Ontario",
#            "Manitoba",
#            "Saskatchewan",
#            "Alberta",
#            "British Columbia",
#            "Yukon",
#            "Northwest Territories",
#            "Nunavut")
# 
# full_data <- df <- tibble(
#   profession_type = character(),
#   year = integer(),
#   count = integer(),
#   count_per_100000 = numeric(),
#   percent_female = numeric(),
#   percent_age_under_30 = numeric(),
#   percent_age_30_to_59 = numeric(),
#   percent_age_over_60 = numeric(),
#   province_territory = character()
# )
# 
# for (i in seq_along(names)) {
#   sheet_number = i + 3
#   
#   data = read_save_process_province_territory_data(
#     sheet_number=sheet_number,
#     name=names[i])
#   
#   full_data <- rbind(full_data, data)
# }
```

```{r}
# population_data <- read.xlsx(
#   "../data/raw/raw_data.xlsx",
#   sheet=17,
#   startRow=2,
#   rows=seq(2, 15)) |>
#   select(1:6)
# 
# colnames(population_data) <- c("province_territory", "2019", "2020", "2021", "2022", "2023")
# 
# population_data <- population_data |>
#   pivot_longer(c("2019", "2020", "2021", "2022", "2023"),
#                names_to="year",
#                values_to = "population") |>
#   mutate(year = as.numeric(year))
```

```{r}
# read_save_process_province_territory_data(
#      sheet_number=6,
#      name="Nova Scotia")
```

```{r}
# raw_ns_data <- read.xlsx(
#   "../data/raw/raw_data.xlsx",
#   sheet=6,
#   startRow=2,
#   rows=seq(2, 185),
#   fillMergedCells = TRUE) |>
#   select(1:8)
# 
# processed_nl_data <- raw_nl_data
# 
# colnames(processed_nl_data) <- c("profession_type",
#                                  "year",
#                                  "count",
#                                  "count_per_100000",
#                                  "percent_female",
#                                  "percent_age_under_30",
#                                  "percent_age_30_to_59",
#                                  "percent_age_over_60") 
# 
# processed_nl_data <- processed_nl_data |>
#   filter(profession_type == "Family medicine" |
#         profession_type == "Nurse practitioners") |>
#   mutate(province_territory = "Nova Scotia")
```

```{r}
# full_data <- full_join(full_data,
#                        population_data,
#                        by = join_by(year, province_territory)
```

```{r}
# head(population_data)
```

```{r}
processed_data_summary <- processed_data |>
  group_by(year, province_territory) |>
  summarize(total_workers = sum(count, na.rm = TRUE),
            total_count_per_100000 = sum(count_per_100000, na.rm=TRUE))
  
```

```{r}
    # "count_per_100000",
    # "percent_female",
    # "percent_age_under_30",
    # "percent_age_30_to_59",
    # "percent_age_over_60"
summary_data <- processed_data |>
  mutate(count_female_per_100000 = count_per_100000 * percent_female / 100,
         count_age_under_30_per_100000 = count_per_100000 * percent_age_under_30 / 100,
         count_age_30_to_59_per_100000 = count_per_100000 * percent_age_30_to_59 / 100,
         count_age_over_60_per_100000 = count_per_100000 * percent_age_over_60 / 100) |>
  group_by(year, province_territory) |>
  # summarize(total_workers = sum(count, na.rm = TRUE),
  #           total_count_per_100000 = sum(count_per_100000, na.rm=TRUE),
  #           total_percent_female = sum(count_female_per_100000, na.rm=TRUE) / total_count_per_100000 * 100,
  #           total_percent_age_under_30 = sum(count_age_under_30_per_100000, na.rm=TRUE) / total_count_per_100000 * 100,
  #           total_percent_age_30_to_59 = sum(count_age_30_to_59_per_100000, na.rm=TRUE) / total_count_per_100000 * 100,
  #           total_percent_age_over_60 = sum(count_age_over_60_per_100000, na.rm=TRUE) / total_count_per_100000 * 100)
  
#   summarize(
#     total_workers = sum(count, na.rm = TRUE),
#     total_count_per_100000 = sum(count_per_100000, na.rm = TRUE),
#     total_percent_female = ifelse(total_count_per_100000 == 0, 0, sum(count_female_per_100000, na.rm = TRUE) / total_count_per_100000 * 100),
#     total_percent_age_under_30 = ifelse(total_count_per_100000 == 0, 0, sum(count_age_under_30_per_100000, na.rm = TRUE) / total_count_per_100000 * 100),
#     total_percent_age_30_to_59 = ifelse(total_count_per_100000 == 0, 0, sum(count_age_30_to_59_per_100000, na.rm = TRUE) / total_count_per_100000 * 100),
#     total_percent_age_over_60 = ifelse(total_count_per_100000 == 0, 0, sum(count_age_over_60_per_100000, na.rm = TRUE) / total_count_per_100000 * 100)
#   )
#   
# write_csv(summary_data, "../data/processed/summary_processed_data.csv")
```

```{r}
# write_csv(full_data, "../data/processed/processed_data.csv")
```

## Development of Visuals

```{r}
# load processed data with the correct dtypes
processed_data <- read_csv("../data/processed/processed_data.csv") |>
  mutate(
    profession_type = as.factor(profession_type),
    province_territory = as.factor(province_territory),
    year = as.numeric(year),
    count = as.numeric(count),
    count_per_100000 = as.numeric(count_per_100000),
    percent_female = as.numeric(percent_female),
    percent_age_under_30 = as.numeric(percent_age_under_30),
    percent_age_30_to_59 = as.numeric(percent_age_30_to_59),
    percent_age_over_60 = as.numeric(percent_age_over_60),
  )
```
```{r}
summary_data <- read_csv("../data/processed/summary_processed_data.csv") |>
  mutate(
    profession_type = as.factor(profession_type),
    province_territory = as.factor(province_territory),
    year = as.numeric(year),
    count = as.numeric(count),
    count_per_100000 = as.numeric(count_per_100000),
    percent_female = as.numeric(percent_female),
    percent_age_under_30 = as.numeric(percent_age_under_30),
    percent_age_30_to_59 = as.numeric(percent_age_30_to_59),
    percent_age_over_60 = as.numeric(percent_age_over_60),
  )
```
```{r}
# new_data <- bind_rows(processed_data, summary_data)
new_data <- read_csv("../data/processed/processed_data.csv") |>
  mutate(
    profession_type = as.factor(profession_type),
    province_territory = as.factor(province_territory),
    year = as.numeric(year),
    count = as.numeric(count),
    count_per_100000 = as.numeric(count_per_100000),
    percent_male = as.numeric(percent_male),
    percent_female = as.numeric(percent_female),
    percent_age_under_30 = as.numeric(percent_age_under_30),
    percent_age_30_to_59 = as.numeric(percent_age_30_to_59),
    percent_age_over_60 = as.numeric(percent_age_over_60),
  )
```

## Line plot of Count of Primary Care Providers per 100,000 Population Over Time Per Province/Territory
```{r}
selected_profession_type <- "Family medicine doctors"
#selected_profession_type <- "All"
#selected_profession_type <- "Nurse practitioners"

new_data |>
  # put filter for selected provinces here
    filter(profession_type == selected_profession_type) |>
    ggplot(aes(x=year, y=count_per_100000, color=province_territory)) +
    geom_line(size = 1) +
    labs(x = "Year",
         y = "Number of Primary Care Providers per 100,000 Population",
         color = "Province/Territory",
         title = "Number of Primary Care Providers per 100,000 Population Over Time") +
    theme_minimal() +
    ggthemes::scale_color_gdocs()

```
## Average Proportion of Primary Care Providers Per Gender Group
```{r}
new_data |>
  # add filter for province / territory
  filter(profession_type == selected_profession_type) |>
  mutate(year = as.factor(year)) |>
  group_by(year) |>
  summarise(percent_female = mean(percent_female, na.rm = TRUE),
            percent_male = mean(percent_male, na.rm = TRUE)) |>
  pivot_longer(cols = c(percent_female, percent_male), 
               names_to = "gender", values_to = "percentage") |>
  mutate(gender = factor(gender, levels = c("percent_male", "percent_female"))) |> 
  ggplot(aes(x = year, y = percentage, fill = gender)) +
  geom_bar(stat = "identity") +  # Single bar call with stacked fill
  scale_fill_manual(values = c("percent_male" = "#0072B2", "percent_female" = "#E69F00"),
                    labels = c("percent_male" = "Male", "percent_female" = "Female")) + 
  labs(x = "Year", y = "Percentage", fill = "Gender",
       title = "Average Proportion of Primary Care Providers Per Gender Group") +
  theme_minimal()
```

## Average Proportion of Primary Care Providers Per Age Group
```{r}
new_data |>
  filter(profession_type == selected_profession_type) |>
  mutate(year = as.factor(year)) |>
  group_by(year) |>
  summarise(percent_age_under_30 = mean(percent_age_under_30, na.rm = TRUE),
            percent_age_30_to_59 = mean(percent_age_30_to_59, na.rm = TRUE),
            percent_age_over_60 = mean(percent_age_over_60, na.rm = TRUE)) |>
  pivot_longer(cols = c(percent_age_under_30, percent_age_30_to_59, percent_age_over_60), 
               names_to = "age_group", values_to = "percentage") |>
  mutate(age_group = factor(age_group, levels = c("percent_age_over_60", "percent_age_30_to_59", "percent_age_under_30"))) |>
  ggplot(aes(x = year, y = percentage, fill = age_group)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("percent_age_under_30" = "#72d660", "percent_age_30_to_59" = "#339ff2", "percent_age_over_60" = "#8b29e6"),
                    labels = c("percent_age_under_30" = "Percent Under 30 Years Old", "percent_age_30_to_59" = "Percent Between 30 and 59 Years Old", "percent_age_over_60" = "Percent Over 60 Years Old")) + 
  labs(x = "Year", y = "Percentage", fill = "Age Group",
       title = "Average Proportion of Primary Care Providers Per Age Group") +
  theme_minimal()
```
